version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "postgres"
    ports:
      - "8000:5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "alkemy"
