version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: api
      MYSQL_USER: alkemy
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
