version: "3.9"

services:
  server:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "postgres"
    ports:
      - "8000:5432"
    environment:
      POSTGRESS_PASSWORD: "123456"
      POSTGRESS_USER: "alkemy"
